# Multi-tenant blog platform configuration
baseURL = 'https://blog.mypp.site/'
languageCode = 'en-us'
title = 'Blog Platform | Create Your Own Blog'
# GitHub Pages multi-tenant setup
relativeURLs = false
canonifyURLs = true
theme = 'PaperMod'

# Platform-specific content
contentDir = 'content-platform'

# Enable multi-tenant features
enableGitInfo = true

[pagination]
  pagerSize = 10

# Multi-tenant blog configuration
[params.platform]
  enableMultiTenant = true
  defaultBlog = 'parada'

[params]
  env = 'production'
  description = 'My personal portfolio showcasing my projects, thoughts, and expertise'
  author = 'Parada'
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    identifier = 'create-blog'
    name = '✨ Create Blog'
    url = '/create-blog/'
    weight = 20
  [[menu.main]]
    identifier = 'parada-blog'
    name = '👤 Parada Blog'
    url = '/parada/'
    weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = 'github'
