# Parada's Personal Blog Configuration
baseURL = 'https://blog.mypp.site/parada/'
languageCode = 'en-us'
title = "Parada's Blog"
# Multi-tenant blog setup
relativeURLs = false
canonifyURLs = true
theme = 'PaperMod'

# Content and static directories (relative to root)
contentDir = '../../content-parada'
staticDir = '../../static'
layoutDir = '../../layouts'
dataDir = '../../data'
themesDir = '../../themes'

# Build settings
enableGitInfo = true

[pagination]
  pagerSize = 10

[params]
  env = 'production'
  description = 'Personal blog by Parada - thoughts, projects, and technical insights'
  author = 'Parada'
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false
  
  # Hide platform banner on personal blog
  hidePlatformBanner = true
  
  # Social links
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/Antonio-Parada"
  
  [[params.socialIcons]]
    name = "linkedin" 
    url = "https://linkedin.com/in/antonio-parada"

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/parada/'
    weight = 10
  [[menu.main]]
    identifier = 'posts'
    name = 'Posts'
    url = '/parada/posts/'
    weight = 20
  [[menu.main]]
    identifier = 'tags'
    name = 'Tags'
    url = '/parada/tags/'
    weight = 30
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/parada/about/'
    weight = 40
  [[menu.main]]
    identifier = 'platform'
    name = '🏠 Platform'
    url = '/'
    weight = 50

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = 'github'
